# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cutlength_fix_tabs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1206, 843)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.upload_button = QtGui.QPushButton(self.centralwidget)
        self.upload_button.setGeometry(QtCore.QRect(610, 730, 181, 51))
        self.upload_button.setMaximumSize(QtCore.QSize(8777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.upload_button.setFont(font)
        self.upload_button.setObjectName(_fromUtf8("upload_button"))
        self.save_data_button = QtGui.QPushButton(self.centralwidget)
        self.save_data_button.setGeometry(QtCore.QRect(420, 730, 181, 51))
        self.save_data_button.setMaximumSize(QtCore.QSize(8777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_data_button.setFont(font)
        self.save_data_button.setStyleSheet(_fromUtf8("background-color: rgb(0, 229, 0);"))
        self.save_data_button.setObjectName(_fromUtf8("save_data_button"))
        self.getDifference = QtGui.QPushButton(self.centralwidget)
        self.getDifference.setGeometry(QtCore.QRect(510, 660, 191, 51))
        self.getDifference.setObjectName(_fromUtf8("getDifference"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 136, 1124, 501))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.straw_0 = QtGui.QLineEdit(self.frame)
        self.straw_0.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_0.setObjectName(_fromUtf8("straw_0"))
        self.verticalLayout.addWidget(self.straw_0)
        self.straw_1 = QtGui.QLineEdit(self.frame)
        self.straw_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_1.setObjectName(_fromUtf8("straw_1"))
        self.verticalLayout.addWidget(self.straw_1)
        self.straw_2 = QtGui.QLineEdit(self.frame)
        self.straw_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_2.setObjectName(_fromUtf8("straw_2"))
        self.verticalLayout.addWidget(self.straw_2)
        self.straw_3 = QtGui.QLineEdit(self.frame)
        self.straw_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_3.setObjectName(_fromUtf8("straw_3"))
        self.verticalLayout.addWidget(self.straw_3)
        self.straw_4 = QtGui.QLineEdit(self.frame)
        self.straw_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_4.setObjectName(_fromUtf8("straw_4"))
        self.verticalLayout.addWidget(self.straw_4)
        self.straw_5 = QtGui.QLineEdit(self.frame)
        self.straw_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_5.setObjectName(_fromUtf8("straw_5"))
        self.verticalLayout.addWidget(self.straw_5)
        self.straw_6 = QtGui.QLineEdit(self.frame)
        self.straw_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_6.setObjectName(_fromUtf8("straw_6"))
        self.verticalLayout.addWidget(self.straw_6)
        self.straw_7 = QtGui.QLineEdit(self.frame)
        self.straw_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_7.setObjectName(_fromUtf8("straw_7"))
        self.verticalLayout.addWidget(self.straw_7)
        self.straw_8 = QtGui.QLineEdit(self.frame)
        self.straw_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_8.setObjectName(_fromUtf8("straw_8"))
        self.verticalLayout.addWidget(self.straw_8)
        self.straw_9 = QtGui.QLineEdit(self.frame)
        self.straw_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_9.setObjectName(_fromUtf8("straw_9"))
        self.verticalLayout.addWidget(self.straw_9)
        self.straw_10 = QtGui.QLineEdit(self.frame)
        self.straw_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_10.setObjectName(_fromUtf8("straw_10"))
        self.verticalLayout.addWidget(self.straw_10)
        self.straw_11 = QtGui.QLineEdit(self.frame)
        self.straw_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.straw_11.setObjectName(_fromUtf8("straw_11"))
        self.verticalLayout.addWidget(self.straw_11)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.error_0 = QtGui.QLineEdit(self.frame)
        self.error_0.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_0.setReadOnly(True)
        self.error_0.setObjectName(_fromUtf8("error_0"))
        self.verticalLayout_3.addWidget(self.error_0)
        self.error_1 = QtGui.QLineEdit(self.frame)
        self.error_1.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_1.setReadOnly(True)
        self.error_1.setObjectName(_fromUtf8("error_1"))
        self.verticalLayout_3.addWidget(self.error_1)
        self.error_2 = QtGui.QLineEdit(self.frame)
        self.error_2.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_2.setReadOnly(True)
        self.error_2.setObjectName(_fromUtf8("error_2"))
        self.verticalLayout_3.addWidget(self.error_2)
        self.error_3 = QtGui.QLineEdit(self.frame)
        self.error_3.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_3.setReadOnly(True)
        self.error_3.setObjectName(_fromUtf8("error_3"))
        self.verticalLayout_3.addWidget(self.error_3)
        self.error_4 = QtGui.QLineEdit(self.frame)
        self.error_4.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_4.setReadOnly(True)
        self.error_4.setObjectName(_fromUtf8("error_4"))
        self.verticalLayout_3.addWidget(self.error_4)
        self.error_5 = QtGui.QLineEdit(self.frame)
        self.error_5.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_5.setReadOnly(True)
        self.error_5.setObjectName(_fromUtf8("error_5"))
        self.verticalLayout_3.addWidget(self.error_5)
        self.error_6 = QtGui.QLineEdit(self.frame)
        self.error_6.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_6.setReadOnly(True)
        self.error_6.setObjectName(_fromUtf8("error_6"))
        self.verticalLayout_3.addWidget(self.error_6)
        self.error_7 = QtGui.QLineEdit(self.frame)
        self.error_7.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_7.setReadOnly(True)
        self.error_7.setObjectName(_fromUtf8("error_7"))
        self.verticalLayout_3.addWidget(self.error_7)
        self.error_8 = QtGui.QLineEdit(self.frame)
        self.error_8.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_8.setReadOnly(True)
        self.error_8.setObjectName(_fromUtf8("error_8"))
        self.verticalLayout_3.addWidget(self.error_8)
        self.error_9 = QtGui.QLineEdit(self.frame)
        self.error_9.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_9.setReadOnly(True)
        self.error_9.setObjectName(_fromUtf8("error_9"))
        self.verticalLayout_3.addWidget(self.error_9)
        self.error_10 = QtGui.QLineEdit(self.frame)
        self.error_10.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_10.setReadOnly(True)
        self.error_10.setObjectName(_fromUtf8("error_10"))
        self.verticalLayout_3.addWidget(self.error_10)
        self.error_11 = QtGui.QLineEdit(self.frame)
        self.error_11.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_11.setReadOnly(True)
        self.error_11.setObjectName(_fromUtf8("error_11"))
        self.verticalLayout_3.addWidget(self.error_11)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_10 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_26.addWidget(self.label_10)
        self.label_9 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_26.addWidget(self.label_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mlen_0 = QtGui.QLineEdit(self.frame)
        self.mlen_0.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_0.setObjectName(_fromUtf8("mlen_0"))
        self.horizontalLayout.addWidget(self.mlen_0)
        self.mlen_64th_0 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_0.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_0.setObjectName(_fromUtf8("mlen_64th_0"))
        self.horizontalLayout.addWidget(self.mlen_64th_0)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mlen_1 = QtGui.QLineEdit(self.frame)
        self.mlen_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_1.setObjectName(_fromUtf8("mlen_1"))
        self.horizontalLayout_2.addWidget(self.mlen_1)
        self.mlen_64th_1 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_1.setObjectName(_fromUtf8("mlen_64th_1"))
        self.horizontalLayout_2.addWidget(self.mlen_64th_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mlen_2 = QtGui.QLineEdit(self.frame)
        self.mlen_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_2.setObjectName(_fromUtf8("mlen_2"))
        self.horizontalLayout_3.addWidget(self.mlen_2)
        self.mlen_64th_2 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_2.setObjectName(_fromUtf8("mlen_64th_2"))
        self.horizontalLayout_3.addWidget(self.mlen_64th_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.mlen_3 = QtGui.QLineEdit(self.frame)
        self.mlen_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_3.setObjectName(_fromUtf8("mlen_3"))
        self.horizontalLayout_4.addWidget(self.mlen_3)
        self.mlen_64th_3 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_3.setObjectName(_fromUtf8("mlen_64th_3"))
        self.horizontalLayout_4.addWidget(self.mlen_64th_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.mlen_4 = QtGui.QLineEdit(self.frame)
        self.mlen_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_4.setObjectName(_fromUtf8("mlen_4"))
        self.horizontalLayout_5.addWidget(self.mlen_4)
        self.mlen_64th_4 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_4.setObjectName(_fromUtf8("mlen_64th_4"))
        self.horizontalLayout_5.addWidget(self.mlen_64th_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.mlen_5 = QtGui.QLineEdit(self.frame)
        self.mlen_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_5.setObjectName(_fromUtf8("mlen_5"))
        self.horizontalLayout_6.addWidget(self.mlen_5)
        self.mlen_64th_5 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_5.setObjectName(_fromUtf8("mlen_64th_5"))
        self.horizontalLayout_6.addWidget(self.mlen_64th_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mlen_6 = QtGui.QLineEdit(self.frame)
        self.mlen_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_6.setObjectName(_fromUtf8("mlen_6"))
        self.horizontalLayout_7.addWidget(self.mlen_6)
        self.mlen_64th_6 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_6.setObjectName(_fromUtf8("mlen_64th_6"))
        self.horizontalLayout_7.addWidget(self.mlen_64th_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.mlen_7 = QtGui.QLineEdit(self.frame)
        self.mlen_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_7.setObjectName(_fromUtf8("mlen_7"))
        self.horizontalLayout_8.addWidget(self.mlen_7)
        self.mlen_64th_7 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_7.setObjectName(_fromUtf8("mlen_64th_7"))
        self.horizontalLayout_8.addWidget(self.mlen_64th_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.mlen_8 = QtGui.QLineEdit(self.frame)
        self.mlen_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_8.setObjectName(_fromUtf8("mlen_8"))
        self.horizontalLayout_9.addWidget(self.mlen_8)
        self.mlen_64th_8 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_8.setObjectName(_fromUtf8("mlen_64th_8"))
        self.horizontalLayout_9.addWidget(self.mlen_64th_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.mlen_9 = QtGui.QLineEdit(self.frame)
        self.mlen_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_9.setObjectName(_fromUtf8("mlen_9"))
        self.horizontalLayout_10.addWidget(self.mlen_9)
        self.mlen_64th_9 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_9.setObjectName(_fromUtf8("mlen_64th_9"))
        self.horizontalLayout_10.addWidget(self.mlen_64th_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.mlen_10 = QtGui.QLineEdit(self.frame)
        self.mlen_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_10.setObjectName(_fromUtf8("mlen_10"))
        self.horizontalLayout_11.addWidget(self.mlen_10)
        self.mlen_64th_10 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_10.setObjectName(_fromUtf8("mlen_64th_10"))
        self.horizontalLayout_11.addWidget(self.mlen_64th_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.mlen_11 = QtGui.QLineEdit(self.frame)
        self.mlen_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_11.setObjectName(_fromUtf8("mlen_11"))
        self.horizontalLayout_12.addWidget(self.mlen_11)
        self.mlen_64th_11 = QtGui.QLineEdit(self.frame)
        self.mlen_64th_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_11.setObjectName(_fromUtf8("mlen_64th_11"))
        self.horizontalLayout_12.addWidget(self.mlen_64th_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 1, 2, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.label.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.layoutWidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.straw_12 = QtGui.QLineEdit(self.frame_3)
        self.straw_12.setObjectName(_fromUtf8("straw_12"))
        self.verticalLayout_2.addWidget(self.straw_12)
        self.straw_13 = QtGui.QLineEdit(self.frame_3)
        self.straw_13.setObjectName(_fromUtf8("straw_13"))
        self.verticalLayout_2.addWidget(self.straw_13)
        self.straw_14 = QtGui.QLineEdit(self.frame_3)
        self.straw_14.setObjectName(_fromUtf8("straw_14"))
        self.verticalLayout_2.addWidget(self.straw_14)
        self.straw_15 = QtGui.QLineEdit(self.frame_3)
        self.straw_15.setObjectName(_fromUtf8("straw_15"))
        self.verticalLayout_2.addWidget(self.straw_15)
        self.straw_16 = QtGui.QLineEdit(self.frame_3)
        self.straw_16.setObjectName(_fromUtf8("straw_16"))
        self.verticalLayout_2.addWidget(self.straw_16)
        self.straw_17 = QtGui.QLineEdit(self.frame_3)
        self.straw_17.setObjectName(_fromUtf8("straw_17"))
        self.verticalLayout_2.addWidget(self.straw_17)
        self.straw_18 = QtGui.QLineEdit(self.frame_3)
        self.straw_18.setObjectName(_fromUtf8("straw_18"))
        self.verticalLayout_2.addWidget(self.straw_18)
        self.straw_19 = QtGui.QLineEdit(self.frame_3)
        self.straw_19.setObjectName(_fromUtf8("straw_19"))
        self.verticalLayout_2.addWidget(self.straw_19)
        self.straw_20 = QtGui.QLineEdit(self.frame_3)
        self.straw_20.setObjectName(_fromUtf8("straw_20"))
        self.verticalLayout_2.addWidget(self.straw_20)
        self.straw_21 = QtGui.QLineEdit(self.frame_3)
        self.straw_21.setObjectName(_fromUtf8("straw_21"))
        self.verticalLayout_2.addWidget(self.straw_21)
        self.straw_22 = QtGui.QLineEdit(self.frame_3)
        self.straw_22.setObjectName(_fromUtf8("straw_22"))
        self.verticalLayout_2.addWidget(self.straw_22)
        self.straw_23 = QtGui.QLineEdit(self.frame_3)
        self.straw_23.setObjectName(_fromUtf8("straw_23"))
        self.verticalLayout_2.addWidget(self.straw_23)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 2, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.error_12 = QtGui.QLineEdit(self.frame_3)
        self.error_12.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_12.setReadOnly(True)
        self.error_12.setObjectName(_fromUtf8("error_12"))
        self.verticalLayout_4.addWidget(self.error_12)
        self.error_13 = QtGui.QLineEdit(self.frame_3)
        self.error_13.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_13.setReadOnly(True)
        self.error_13.setObjectName(_fromUtf8("error_13"))
        self.verticalLayout_4.addWidget(self.error_13)
        self.error_14 = QtGui.QLineEdit(self.frame_3)
        self.error_14.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_14.setReadOnly(True)
        self.error_14.setObjectName(_fromUtf8("error_14"))
        self.verticalLayout_4.addWidget(self.error_14)
        self.error_15 = QtGui.QLineEdit(self.frame_3)
        self.error_15.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_15.setReadOnly(True)
        self.error_15.setObjectName(_fromUtf8("error_15"))
        self.verticalLayout_4.addWidget(self.error_15)
        self.error_16 = QtGui.QLineEdit(self.frame_3)
        self.error_16.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_16.setReadOnly(True)
        self.error_16.setObjectName(_fromUtf8("error_16"))
        self.verticalLayout_4.addWidget(self.error_16)
        self.error_17 = QtGui.QLineEdit(self.frame_3)
        self.error_17.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_17.setReadOnly(True)
        self.error_17.setObjectName(_fromUtf8("error_17"))
        self.verticalLayout_4.addWidget(self.error_17)
        self.error_18 = QtGui.QLineEdit(self.frame_3)
        self.error_18.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_18.setReadOnly(True)
        self.error_18.setObjectName(_fromUtf8("error_18"))
        self.verticalLayout_4.addWidget(self.error_18)
        self.error_19 = QtGui.QLineEdit(self.frame_3)
        self.error_19.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_19.setReadOnly(True)
        self.error_19.setObjectName(_fromUtf8("error_19"))
        self.verticalLayout_4.addWidget(self.error_19)
        self.error_20 = QtGui.QLineEdit(self.frame_3)
        self.error_20.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_20.setReadOnly(True)
        self.error_20.setObjectName(_fromUtf8("error_20"))
        self.verticalLayout_4.addWidget(self.error_20)
        self.error_21 = QtGui.QLineEdit(self.frame_3)
        self.error_21.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_21.setReadOnly(True)
        self.error_21.setObjectName(_fromUtf8("error_21"))
        self.verticalLayout_4.addWidget(self.error_21)
        self.error_22 = QtGui.QLineEdit(self.frame_3)
        self.error_22.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_22.setReadOnly(True)
        self.error_22.setObjectName(_fromUtf8("error_22"))
        self.verticalLayout_4.addWidget(self.error_22)
        self.error_23 = QtGui.QLineEdit(self.frame_3)
        self.error_23.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.error_23.setReadOnly(True)
        self.error_23.setObjectName(_fromUtf8("error_23"))
        self.verticalLayout_4.addWidget(self.error_23)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 2, 2, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_25.addWidget(self.label_6)
        self.label_8 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_25.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_25, 1, 1, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.mlen_12 = QtGui.QLineEdit(self.frame_3)
        self.mlen_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_12.setObjectName(_fromUtf8("mlen_12"))
        self.horizontalLayout_13.addWidget(self.mlen_12)
        self.mlen_64th_12 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_12.setObjectName(_fromUtf8("mlen_64th_12"))
        self.horizontalLayout_13.addWidget(self.mlen_64th_12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.mlen_13 = QtGui.QLineEdit(self.frame_3)
        self.mlen_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_13.setObjectName(_fromUtf8("mlen_13"))
        self.horizontalLayout_14.addWidget(self.mlen_13)
        self.mlen_64th_13 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_13.setObjectName(_fromUtf8("mlen_64th_13"))
        self.horizontalLayout_14.addWidget(self.mlen_64th_13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.mlen_14 = QtGui.QLineEdit(self.frame_3)
        self.mlen_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_14.setObjectName(_fromUtf8("mlen_14"))
        self.horizontalLayout_15.addWidget(self.mlen_14)
        self.mlen_64th_14 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_14.setObjectName(_fromUtf8("mlen_64th_14"))
        self.horizontalLayout_15.addWidget(self.mlen_64th_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.mlen_15 = QtGui.QLineEdit(self.frame_3)
        self.mlen_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_15.setObjectName(_fromUtf8("mlen_15"))
        self.horizontalLayout_16.addWidget(self.mlen_15)
        self.mlen_64th_15 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_15.setObjectName(_fromUtf8("mlen_64th_15"))
        self.horizontalLayout_16.addWidget(self.mlen_64th_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.mlen_16 = QtGui.QLineEdit(self.frame_3)
        self.mlen_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_16.setObjectName(_fromUtf8("mlen_16"))
        self.horizontalLayout_17.addWidget(self.mlen_16)
        self.mlen_64th_16 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_16.setObjectName(_fromUtf8("mlen_64th_16"))
        self.horizontalLayout_17.addWidget(self.mlen_64th_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.mlen_17 = QtGui.QLineEdit(self.frame_3)
        self.mlen_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_17.setObjectName(_fromUtf8("mlen_17"))
        self.horizontalLayout_18.addWidget(self.mlen_17)
        self.mlen_64th_17 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_17.setObjectName(_fromUtf8("mlen_64th_17"))
        self.horizontalLayout_18.addWidget(self.mlen_64th_17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.mlen_18 = QtGui.QLineEdit(self.frame_3)
        self.mlen_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_18.setObjectName(_fromUtf8("mlen_18"))
        self.horizontalLayout_19.addWidget(self.mlen_18)
        self.mlen_64th_18 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_18.setObjectName(_fromUtf8("mlen_64th_18"))
        self.horizontalLayout_19.addWidget(self.mlen_64th_18)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.mlen_19 = QtGui.QLineEdit(self.frame_3)
        self.mlen_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_19.setObjectName(_fromUtf8("mlen_19"))
        self.horizontalLayout_20.addWidget(self.mlen_19)
        self.mlen_64th_19 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_19.setObjectName(_fromUtf8("mlen_64th_19"))
        self.horizontalLayout_20.addWidget(self.mlen_64th_19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.mlen_20 = QtGui.QLineEdit(self.frame_3)
        self.mlen_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_20.setObjectName(_fromUtf8("mlen_20"))
        self.horizontalLayout_21.addWidget(self.mlen_20)
        self.mlen_64th_20 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_20.setObjectName(_fromUtf8("mlen_64th_20"))
        self.horizontalLayout_21.addWidget(self.mlen_64th_20)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.mlen_21 = QtGui.QLineEdit(self.frame_3)
        self.mlen_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_21.setObjectName(_fromUtf8("mlen_21"))
        self.horizontalLayout_22.addWidget(self.mlen_21)
        self.mlen_64th_21 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_21.setObjectName(_fromUtf8("mlen_64th_21"))
        self.horizontalLayout_22.addWidget(self.mlen_64th_21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.mlen_22 = QtGui.QLineEdit(self.frame_3)
        self.mlen_22.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_22.setObjectName(_fromUtf8("mlen_22"))
        self.horizontalLayout_23.addWidget(self.mlen_22)
        self.mlen_64th_22 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_22.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_22.setObjectName(_fromUtf8("mlen_64th_22"))
        self.horizontalLayout_23.addWidget(self.mlen_64th_22)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.mlen_23 = QtGui.QLineEdit(self.frame_3)
        self.mlen_23.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_23.setObjectName(_fromUtf8("mlen_23"))
        self.horizontalLayout_24.addWidget(self.mlen_23)
        self.mlen_64th_23 = QtGui.QLineEdit(self.frame_3)
        self.mlen_64th_23.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mlen_64th_23.setObjectName(_fromUtf8("mlen_64th_23"))
        self.horizontalLayout_24.addWidget(self.mlen_64th_23)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.gridLayout.addLayout(self.verticalLayout_6, 2, 1, 2, 1)
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_11.raise_()
        self.gridLayout_5.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 40, 721, 86))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(12, 11, 691, 66))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.worker_barcode1 = QtGui.QLineEdit(self.widget)
        self.worker_barcode1.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.worker_barcode1.setObjectName(_fromUtf8("worker_barcode1"))
        self.horizontalLayout_27.addWidget(self.worker_barcode1)
        self.worker_barcode2 = QtGui.QLineEdit(self.widget)
        self.worker_barcode2.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.worker_barcode2.setObjectName(_fromUtf8("worker_barcode2"))
        self.horizontalLayout_27.addWidget(self.worker_barcode2)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_27.addWidget(self.label_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.lowest_st = QtGui.QLineEdit(self.widget)
        self.lowest_st.setObjectName(_fromUtf8("lowest_st"))
        self.horizontalLayout_28.addWidget(self.lowest_st)
        self.highest_st = QtGui.QLineEdit(self.widget)
        self.highest_st.setObjectName(_fromUtf8("highest_st"))
        self.horizontalLayout_28.addWidget(self.highest_st)
        self.panelType = QtGui.QComboBox(self.widget)
        self.panelType.setObjectName(_fromUtf8("panelType"))
        self.panelType.addItem(_fromUtf8(""))
        self.panelType.setItemText(0, _fromUtf8(""))
        self.panelType.addItem(_fromUtf8(""))
        self.panelType.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.panelType)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 1, 0, 1, 1)
        self.layoutWidget.raise_()
        self.upload_button.raise_()
        self.save_data_button.raise_()
        self.getDifference.raise_()
        self.mlen_12.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1206, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.upload_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.upload_data)
        QtCore.QObject.connect(self.save_data_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.save_data)
        QtCore.QObject.connect(self.panelType, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.fill_info)
        QtCore.QObject.connect(self.getDifference, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.getError)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.upload_button.setText(_translate("MainWindow", "Upload data", None))
        self.save_data_button.setText(_translate("MainWindow", "Save data", None))
        self.getDifference.setText(_translate("MainWindow", "Get differences", None))
        self.label.setText(_translate("MainWindow", "Straw", None))
        self.label_5.setText(_translate("MainWindow", "Measured", None))
        self.label_10.setText(_translate("MainWindow", "(Inch)", None))
        self.label_9.setText(_translate("MainWindow", "(1/64\")", None))
        self.label_3.setText(_translate("MainWindow", "Difference From Intended (1/64\")", None))
        self.label_4.setText(_translate("MainWindow", "Straw", None))
        self.label_11.setText(_translate("MainWindow", "Difference From Intended(1/64\")", None))
        self.label_2.setText(_translate("MainWindow", "Measured", None))
        self.label_6.setText(_translate("MainWindow", "(Inch)", None))
        self.label_8.setText(_translate("MainWindow", "1/64 inch", None))
        self.worker_barcode1.setPlaceholderText(_translate("MainWindow", "worker barcode", None))
        self.worker_barcode2.setPlaceholderText(_translate("MainWindow", "worker barcode", None))
        self.label_7.setText(_translate("MainWindow", "Panel Type", None))
        self.lowest_st.setPlaceholderText(_translate("MainWindow", "lowest straw", None))
        self.highest_st.setPlaceholderText(_translate("MainWindow", "highest straw", None))
        self.panelType.setItemText(1, _translate("MainWindow", "0, 4", None))
        self.panelType.setItemText(2, _translate("MainWindow", "2, 6", None))

